project:
  type: website
  resources:
      - Drew_CV.pdf

website:
  title: "Lane Drew"
  image: images/IMG_2598.jpg
  google-analytics: "G-GL720ELQZ1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
    right:
      - href: Drew_CV.pdf
        text: C.V.
      - href: https://github.com/lanedrew
        icon: github
      - href: https://www.linkedin.com/in/lanedrew/
        icon: linkedin

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    site: "https://lanedrew.github.io/lanedrew/"

editor: visual

