name: Deploy Quarto site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.6.42

      - name: Install Pandoc (if needed)
        run: sudo apt-get install -y pandoc

      - name: Install R and dependencies
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'

      - name: Render Quarto Project
        run: quarto render

      - name: Create CNAME file
        run: echo "www.lanedrew.com" > _site/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
